version: '3.8'

services:
  frontend:
    build:
      context: ./front-end 
      - "3000:3000"  
    volumes:
      - ./front-end:/app  
      - /app/node_modules  
    stdin_open: true  
    tty: true  
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  ai-job:
    build: ./ai-job
    volumes:
      - ./ai-job:/app
    restart: always  