version: "3.8"

services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"  # Exposes backend on port 5000
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"  # Exposes frontend on port 3000
    depends_on:
      - backend
    networks:
      - app-network

  ai:
    build: ./Ai
    ports:
      - "8000:8000"  # AI model runs on port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
