apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  replicas: 1  # Run a single instance
  selector:
    matchLabels:
      app: react-container
  template:
    metadata:
      labels:
        app: react-container
    spec:
      containers:
      - name: react-container
        image: react-frontend:latest  # Change if pushing to a registry
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
